# Generated by Django 4.1.1 on 2022-09-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0006_alter_department_id_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="workers_count",
        ),
    ]
