# Generated by Django 4.1.1 on 2022-09-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0007_remove_department_workers_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="id_manager",
        ),
    ]
