# Generated by Django 4.1.1 on 2022-09-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_rename_id_position_worker_position_worker_department"),
        ("departments", "0009_departmentmanager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmanager",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
            ),
        ),
        migrations.AlterField(
            model_name="departmentmanager",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workers.worker",
            ),
        ),
    ]
