# Generated by Django 4.1.1 on 2022-09-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_number",
                    models.IntegerField(default="0", unique=True),
                ),
                ("surname", models.CharField(blank=True, default="", max_length=100)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "passport",
                    models.CharField(
                        blank=True, default="", max_length=20, unique=True
                    ),
                ),
                ("work_years", models.IntegerField(blank=True, default="0")),
                ("birth_date", models.DateField(blank=True)),
                (
                    "birth_place",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_street",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("address_house_number", models.IntegerField(blank=True, default="0")),
                (
                    "address_house_letter",
                    models.CharField(blank=True, default="", max_length=5),
                ),
                ("vacation_days_left", models.IntegerField(blank=True, default="0")),
                (
                    "id_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
            },
        ),
    ]
