# Generated by Django 4.1.1 on 2022-09-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
        ("workers", "0002_alter_worker_id_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="id_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="positions.position",
            ),
        ),
    ]
