# Generated by Django 4.1.1 on 2022-09-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0008_remove_department_id_manager"),
        ("workers", "0003_alter_worker_id_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="id_position",
            new_name="position",
        ),
        migrations.AddField(
            model_name="worker",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departments.department",
            ),
        ),
    ]
