# Generated by Django 4.1.1 on 2022-09-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0002_alter_worker_id_position"),
        ("vacations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="id_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workers.worker",
            ),
        ),
    ]
